# Generated by Django 4.0.5 on 2023-05-27 23:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='cname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cour',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cour',
            name='category',
            field=models.CharField(choices=[('Les Nombres', 'Les Nombres'), ('Alphabet', 'Alphabet'), ('Interactive', 'Interactive')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cour',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.client'),
        ),
    ]
