# Generated by Django 4.0.5 on 2023-05-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_client_cage_client_cname_client_email_client_pname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cage',
            new_name='Child_age',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cname',
            new_name='Child_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='pname',
            new_name='Parent_name',
        ),
    ]
