# Generated by Django 5.0.4 on 2024-04-27 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parent_name', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('Child_name', models.CharField(max_length=30, null=True)),
                ('Child_age', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Les Nombres', 'Les Nombres'), ('Alphabet', 'Alphabet'), ('Interactive', 'Interactive')], max_length=30, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='E_Learning_App.client')),
            ],
        ),
    ]
