# Generated by Django 5.1.2 on 2024-10-27 14:08

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Learning_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', embed_video.fields.EmbedVideoField(null=True)),
                ('Video_Category', models.CharField(choices=[('Les Nombres', 'Les Nombres'), ('Alphabet', 'Alphabet'), ('Interactive', 'Interactive')], max_length=30, null=True)),
            ],
        ),
    ]
